-- ============================================================================
-- COMBINED_DEPLOY_21to22_13Aug2026.sql
--
--   ⚡ RUN THIS ONE FILE. ⚡
--
-- Contains PATCH_21 + PATCH_22, generated by concatenation so it cannot drift
-- from the source patches. Adds multi-point geofencing: the plant is no
-- longer a single center point + 100m radius, it's 12 named campus points
-- (Plant location, Office 1st Floor, 9 shops, Raw Material, Store) and
-- check-in succeeds within 100m of ANY of them. worker/home.tsx and
-- fraud-detector already read this table and fall back to the old
-- single-point plant_config geofence automatically if it's empty, so this
-- is a pure addition — nothing about existing check-ins changes except
-- that Machine shop (131m from the old single center point — outside the
-- old 100m radius) now correctly counts.
--
-- ALREADY APPLIED, do NOT re-run: FINAL_SCHEMA, the seeds, PATCH_01..09,
-- COMBINED_DEPLOY_03to09, PATCH_10 (PIN auth), COMBINED_DEPLOY_11to12,
-- COMBINED_DEPLOY_13to15, PATCH_16, PATCH_17, PATCH_18.
-- ============================================================================

-- ── PATCH_21 ──────────────────────────────────────────────────────────────

-- ============================================================================
-- PATCH_21_plant_locations_13Aug2026.sql
--
-- Adds multi-point geofencing. Yash shared a sheet of 11 named locations
-- across the campus (Plant location, Office 1st Floor, Machine shop, Die
-- shop, VMC shop, Press Shop, HT shop, Forge shop, Cutting shop, Final Shop,
-- Raw Material) as Google Maps links. Decision (13 Aug): "multi-point, any
-- match" — a check-in succeeds if the employee is within radius of ANY of
-- these points, not tied to their own department. The single campus is
-- large enough that one center point + 100m (plant_config) was missing
-- far-flung shops like the Raw Material yard.
--
-- This patch only creates the TABLE — it seeds ZERO rows. The Google Maps
-- links resolve to real GPS coordinates, and this sandbox's network egress
-- proxy blocks every Google Maps domain (maps.app.goo.gl, google.com/maps),
-- so those coordinates could not be read here — writing guessed lat/lng
-- values into a table that gates physical plant access would be worse than
-- leaving it empty. The app and fraud-detector both already fall back
-- automatically to the existing single-point plant_config geofence when
-- this table is empty, so running this patch now is safe and changes
-- nothing about current behaviour. Once real coordinates are provided,
-- PATCH_22 will insert the 11 rows and check-in switches over automatically
-- — no further app code changes needed.
-- ============================================================================

create table if not exists plant_locations (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  latitude double precision not null,
  longitude double precision not null,
  radius_meters integer not null default 100,
  is_active boolean not null default true,
  created_at timestamptz default now()
);

create index if not exists idx_plant_locations_active on plant_locations(is_active);

alter table plant_locations enable row level security;

-- Readable by any signed-in employee, same as plant_config — the app needs
-- this list client-side to run the geofence check before it even attempts
-- check-in.
drop policy if exists "plant_locations_select" on plant_locations;
create policy "plant_locations_select" on plant_locations for select using (auth.uid() is not null);

-- Only management can add/edit/remove locations — same rationale as every
-- other config-shaped table in this schema (plant_config has no client
-- write path at all; this is more permissive only because a shop can
-- reasonably be added between SQL sessions without redeploying).
drop policy if exists "plant_locations_write_management" on plant_locations;
create policy "plant_locations_write_management" on plant_locations for all
  using (is_management())
  with check (is_management());

-- ---------------------------------------------------------------------------
-- Verify
-- ---------------------------------------------------------------------------
select 'plant_locations table created, 0 rows (expected — see header comment)' as status,
       count(*) as row_count
from plant_locations;

-- ── PATCH_22 ──────────────────────────────────────────────────────────────

-- ============================================================================
-- PATCH_22_plant_locations_seed_13Aug2026.sql
--
-- Seeds plant_locations (created by PATCH_21, run that one first) with the
-- 12 campus points Yash surveyed and sent as a CSV with coordinates already
-- resolved (this sandbox cannot reach any Google Maps domain to resolve the
-- links itself — see PENDING.md). "Store" is a 12th point that wasn't in
-- the original 11-location sheet but was included in the coordinates file,
-- so it's seeded too.
--
-- Sanity-checked before writing this (not just pasted blind): every point
-- is within 131m of "Plant location" (Machine shop is the farthest, at
-- 131.3m — which means it sat just OUTSIDE the old single-point 100m
-- geofence, a real, concrete case this multi-point upgrade fixes). One
-- oddity worth knowing about: "Cutting shop" and "Final Shop" were sent
-- with IDENTICAL coordinates (19.836111, 75.236750) — seeded as given since
-- it doesn't break anything (both still independently widen the "any
-- match" set to the same physical spot), but flagging it in case that's a
-- copy-paste slip in the source sheet rather than a real coincidence — see
-- PENDING.md.
--
-- Radius: 100m per point, matching the existing plant_config default —
-- deliberately not tightened per-shop, since the design intent (13 Aug
-- decision) is broad "any of these counts" coverage, not per-shop access
-- control.
-- ============================================================================

insert into plant_locations (name, latitude, longitude, radius_meters) values
  ('Plant location',   19.836056, 75.236222, 100),
  ('Office 1st Floor', 19.835928, 75.236184, 100),
  ('Machine shop',     19.835944, 75.237472, 100),
  ('Die shop',         19.836139, 75.236611, 100),
  ('VMC shop',         19.836167, 75.236472, 100),
  ('Press Shop',       19.836222, 75.236444, 100),
  ('HT shop',          19.836139, 75.236556, 100),
  ('Forge shop',       19.836306, 75.236500, 100),
  ('Cutting shop',     19.836111, 75.236750, 100),
  ('Final Shop',       19.836111, 75.236750, 100),
  ('Raw Material',     19.836083, 75.236833, 100),
  ('Store',            19.836109, 75.236702, 100)
on conflict (name) do update set
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  radius_meters = excluded.radius_meters;

-- ---------------------------------------------------------------------------
-- Verify — expect 12 rows, all is_active
-- ---------------------------------------------------------------------------
select name, latitude, longitude, radius_meters, is_active from plant_locations order by name;
